### ISSUE TITLE
How to train from scratch using multiple GPUs?

### ISSUE THREAD

**Issue by le-wei** [SudeepDasari/dit-policy#1]
Thank you very much for the work you have done. Recently, I have been reading your papers and studying your code. The paper mentions that language information is encoded through BERT and then fused with image features via FiLM. However, I couldn’t find the relevant implementation in the code. I would like to add some additional data to the BiPlay dataset and retrain. Should I still use the `finetune` file and the related configuration? How can I train with multiple GPUs? Looking forward to your answer. Thanks again for your work.

**Comment by SudeepDasari** [comment]
You'd have to implement [DDP](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) to get multi-GPU training on pytorch working. It should be a relatively straightforward modification to `finetune.py`. If you'd like to contribute this change, I'd love to add it back to the repo!

**Comment by le-wei** [comment]
Thank you very much! I am using Accelerate to implement parallel training. If the testing results are satisfactory, I will submit a request.
